/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/rest/EntityResource.java.e.vm
 */
package com.mycompany.myapp.rest;

import static org.springframework.http.MediaType.APPLICATION_JSON_VALUE;
import static org.springframework.web.bind.annotation.RequestMethod.DELETE;
import static org.springframework.web.bind.annotation.RequestMethod.GET;
import static org.springframework.web.bind.annotation.RequestMethod.POST;
import static org.springframework.web.bind.annotation.RequestMethod.PUT;

import java.net.URI;
import java.net.URISyntaxException;
import java.util.List;
import java.util.Optional;

import javax.inject.Inject;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.bind.annotation.RequestBody;

import com.mycompany.myapp.domain.DisTable;
import com.mycompany.myapp.dto.DisTableDTO;
import com.mycompany.myapp.dto.DisTableDTOService;
import com.mycompany.myapp.dto.support.PageRequestByExample;
import com.mycompany.myapp.dto.support.PageResponse;
import com.mycompany.myapp.repository.DisTableRepository;
import com.mycompany.myapp.rest.support.AutoCompleteQuery;

@RestController
@RequestMapping("/api/disTables")
public class DisTableResource {

    private final Logger log = LoggerFactory.getLogger(DisTableResource.class);

    @Inject
    private DisTableRepository disTableRepository;
    @Inject
    private DisTableDTOService disTableDTOService;

    /**
     * Create a new DisTable.
     */
    @RequestMapping(value = "/", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<DisTableDTO> create(@RequestBody DisTableDTO disTableDTO) throws URISyntaxException {

        log.debug("Create DisTableDTO : {}", disTableDTO);

        if (disTableDTO.isIdSet()) {
            return ResponseEntity.badRequest().header("Failure", "Cannot create DisTable with existing ID").body(null);
        }

        DisTableDTO result = disTableDTOService.save(disTableDTO);

        return ResponseEntity.created(new URI("/api/disTables/" + result.id)).body(result);
    }

    /**
    * Find by id DisTable.
    */
    @RequestMapping(value = "/{id}", method = GET, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<DisTableDTO> findById(@PathVariable Integer id) throws URISyntaxException {

        log.debug("Find by id DisTable : {}", id);

        return Optional.ofNullable(disTableDTOService.findOne(id)).map(disTableDTO -> new ResponseEntity<>(disTableDTO, HttpStatus.OK))
                .orElse(new ResponseEntity<>(HttpStatus.NOT_FOUND));
    }

    /**
     * Update DisTable.
     */
    @RequestMapping(value = "/", method = PUT, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<DisTableDTO> update(@RequestBody DisTableDTO disTableDTO) throws URISyntaxException {

        log.debug("Update DisTableDTO : {}", disTableDTO);

        if (!disTableDTO.isIdSet()) {
            return create(disTableDTO);
        }

        DisTableDTO result = disTableDTOService.save(disTableDTO);

        return ResponseEntity.ok().body(result);
    }

    /**
     * Find a Page of DisTable using query by example.
     */
    @RequestMapping(value = "/page", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<PageResponse<DisTableDTO>> findAll(@RequestBody PageRequestByExample<DisTableDTO> prbe) throws URISyntaxException {
        PageResponse<DisTableDTO> pageResponse = disTableDTOService.findAll(prbe);
        return new ResponseEntity<>(pageResponse, new HttpHeaders(), HttpStatus.OK);
    }

    /**
    * Auto complete support.
    */
    @RequestMapping(value = "/complete", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<List<DisTableDTO>> complete(@RequestBody AutoCompleteQuery acq) throws URISyntaxException {

        List<DisTableDTO> results = disTableDTOService.complete(acq.query, acq.maxResults);

        return new ResponseEntity<>(results, new HttpHeaders(), HttpStatus.OK);
    }

    /**
     * Delete by id DisTable.
     */
    @RequestMapping(value = "/{id}", method = DELETE, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<Void> delete(@PathVariable Integer id) throws URISyntaxException {

        log.debug("Delete by id DisTable : {}", id);

        try {
            disTableRepository.delete(id);
            return ResponseEntity.ok().build();
        } catch (Exception x) {
            // todo: dig exception, most likely org.hibernate.exception.ConstraintViolationException
            return ResponseEntity.status(HttpStatus.CONFLICT).build();
        }
    }
}