/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/rest/EntityResource.java.e.vm
 */
package com.mycompany.myapp.rest;

import static org.springframework.http.MediaType.APPLICATION_JSON_VALUE;
import static org.springframework.web.bind.annotation.RequestMethod.DELETE;
import static org.springframework.web.bind.annotation.RequestMethod.GET;
import static org.springframework.web.bind.annotation.RequestMethod.POST;
import static org.springframework.web.bind.annotation.RequestMethod.PUT;

import java.net.URI;
import java.net.URISyntaxException;
import java.util.List;
import java.util.Optional;

import javax.inject.Inject;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.bind.annotation.RequestBody;

import com.mycompany.myapp.domain.Logindetails;
import com.mycompany.myapp.dto.LogindetailsDTO;
import com.mycompany.myapp.dto.LogindetailsDTOService;
import com.mycompany.myapp.dto.support.PageRequestByExample;
import com.mycompany.myapp.dto.support.PageResponse;
import com.mycompany.myapp.repository.LogindetailsRepository;
import com.mycompany.myapp.rest.support.AutoCompleteQuery;

@RestController
@RequestMapping("/api/logindetailss")
public class LogindetailsResource {

    private final Logger log = LoggerFactory.getLogger(LogindetailsResource.class);

    @Inject
    private LogindetailsRepository logindetailsRepository;
    @Inject
    private LogindetailsDTOService logindetailsDTOService;

    /**
     * Create a new Logindetails.
     */
    @RequestMapping(value = "/", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<LogindetailsDTO> create(@RequestBody LogindetailsDTO logindetailsDTO) throws URISyntaxException {

        log.debug("Create LogindetailsDTO : {}", logindetailsDTO);

        if (logindetailsDTO.isIdSet()) {
            return ResponseEntity.badRequest().header("Failure", "Cannot create Logindetails with existing ID").body(null);
        }

        LogindetailsDTO result = logindetailsDTOService.save(logindetailsDTO);

        return ResponseEntity.created(new URI("/api/logindetailss/" + result.id)).body(result);
    }

    /**
    * Find by id Logindetails.
    */
    @RequestMapping(value = "/{id}", method = GET, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<LogindetailsDTO> findById(@PathVariable String id) throws URISyntaxException {

        log.debug("Find by id Logindetails : {}", id);

        return Optional.ofNullable(logindetailsDTOService.findOne(id)).map(logindetailsDTO -> new ResponseEntity<>(logindetailsDTO, HttpStatus.OK))
                .orElse(new ResponseEntity<>(HttpStatus.NOT_FOUND));
    }

    /**
     * Update Logindetails.
     */
    @RequestMapping(value = "/", method = PUT, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<LogindetailsDTO> update(@RequestBody LogindetailsDTO logindetailsDTO) throws URISyntaxException {

        log.debug("Update LogindetailsDTO : {}", logindetailsDTO);

        if (!logindetailsDTO.isIdSet()) {
            return create(logindetailsDTO);
        }

        LogindetailsDTO result = logindetailsDTOService.save(logindetailsDTO);

        return ResponseEntity.ok().body(result);
    }

    /**
     * Find a Page of Logindetails using query by example.
     */
    @RequestMapping(value = "/page", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<PageResponse<LogindetailsDTO>> findAll(@RequestBody PageRequestByExample<LogindetailsDTO> prbe) throws URISyntaxException {
        PageResponse<LogindetailsDTO> pageResponse = logindetailsDTOService.findAll(prbe);
        return new ResponseEntity<>(pageResponse, new HttpHeaders(), HttpStatus.OK);
    }

    /**
    * Auto complete support.
    */
    @RequestMapping(value = "/complete", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<List<LogindetailsDTO>> complete(@RequestBody AutoCompleteQuery acq) throws URISyntaxException {

        List<LogindetailsDTO> results = logindetailsDTOService.complete(acq.query, acq.maxResults);

        return new ResponseEntity<>(results, new HttpHeaders(), HttpStatus.OK);
    }

    /**
     * Delete by id Logindetails.
     */
    @RequestMapping(value = "/{id}", method = DELETE, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<Void> delete(@PathVariable String id) throws URISyntaxException {

        log.debug("Delete by id Logindetails : {}", id);

        try {
            logindetailsRepository.delete(id);
            return ResponseEntity.ok().build();
        } catch (Exception x) {
            // todo: dig exception, most likely org.hibernate.exception.ConstraintViolationException
            return ResponseEntity.status(HttpStatus.CONFLICT).build();
        }
    }
}