/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/rest/EntityResource.java.e.vm
 */
package com.mycompany.myapp.rest;

import static org.springframework.http.MediaType.APPLICATION_JSON_VALUE;
import static org.springframework.web.bind.annotation.RequestMethod.DELETE;
import static org.springframework.web.bind.annotation.RequestMethod.GET;
import static org.springframework.web.bind.annotation.RequestMethod.POST;
import static org.springframework.web.bind.annotation.RequestMethod.PUT;

import java.net.URI;
import java.net.URISyntaxException;
import java.util.List;
import java.util.Optional;

import javax.inject.Inject;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.bind.annotation.RequestBody;

import com.mycompany.myapp.domain.ManuTable;
import com.mycompany.myapp.dto.ManuTableDTO;
import com.mycompany.myapp.dto.ManuTableDTOService;
import com.mycompany.myapp.dto.support.PageRequestByExample;
import com.mycompany.myapp.dto.support.PageResponse;
import com.mycompany.myapp.repository.ManuTableRepository;
import com.mycompany.myapp.rest.support.AutoCompleteQuery;

@RestController
@RequestMapping("/api/manuTables")
public class ManuTableResource {

    private final Logger log = LoggerFactory.getLogger(ManuTableResource.class);

    @Inject
    private ManuTableRepository manuTableRepository;
    @Inject
    private ManuTableDTOService manuTableDTOService;

    /**
     * Create a new ManuTable.
     */
    @RequestMapping(value = "/", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<ManuTableDTO> create(@RequestBody ManuTableDTO manuTableDTO) throws URISyntaxException {

        log.debug("Create ManuTableDTO : {}", manuTableDTO);

        if (manuTableDTO.isIdSet()) {
            return ResponseEntity.badRequest().header("Failure", "Cannot create ManuTable with existing ID").body(null);
        }

        ManuTableDTO result = manuTableDTOService.save(manuTableDTO);

        return ResponseEntity.created(new URI("/api/manuTables/" + result.id)).body(result);
    }

    /**
    * Find by id ManuTable.
    */
    @RequestMapping(value = "/{id}", method = GET, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<ManuTableDTO> findById(@PathVariable Integer id) throws URISyntaxException {

        log.debug("Find by id ManuTable : {}", id);

        return Optional.ofNullable(manuTableDTOService.findOne(id)).map(manuTableDTO -> new ResponseEntity<>(manuTableDTO, HttpStatus.OK))
                .orElse(new ResponseEntity<>(HttpStatus.NOT_FOUND));
    }

    /**
     * Update ManuTable.
     */
    @RequestMapping(value = "/", method = PUT, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<ManuTableDTO> update(@RequestBody ManuTableDTO manuTableDTO) throws URISyntaxException {

        log.debug("Update ManuTableDTO : {}", manuTableDTO);

        if (!manuTableDTO.isIdSet()) {
            return create(manuTableDTO);
        }

        ManuTableDTO result = manuTableDTOService.save(manuTableDTO);

        return ResponseEntity.ok().body(result);
    }

    /**
     * Find a Page of ManuTable using query by example.
     */
    @RequestMapping(value = "/page", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<PageResponse<ManuTableDTO>> findAll(@RequestBody PageRequestByExample<ManuTableDTO> prbe) throws URISyntaxException {
        PageResponse<ManuTableDTO> pageResponse = manuTableDTOService.findAll(prbe);
        return new ResponseEntity<>(pageResponse, new HttpHeaders(), HttpStatus.OK);
    }

    /**
    * Auto complete support.
    */
    @RequestMapping(value = "/complete", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<List<ManuTableDTO>> complete(@RequestBody AutoCompleteQuery acq) throws URISyntaxException {

        List<ManuTableDTO> results = manuTableDTOService.complete(acq.query, acq.maxResults);

        return new ResponseEntity<>(results, new HttpHeaders(), HttpStatus.OK);
    }

    /**
     * Delete by id ManuTable.
     */
    @RequestMapping(value = "/{id}", method = DELETE, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<Void> delete(@PathVariable Integer id) throws URISyntaxException {

        log.debug("Delete by id ManuTable : {}", id);

        try {
            manuTableRepository.delete(id);
            return ResponseEntity.ok().build();
        } catch (Exception x) {
            // todo: dig exception, most likely org.hibernate.exception.ConstraintViolationException
            return ResponseEntity.status(HttpStatus.CONFLICT).build();
        }
    }
}