/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/rest/EntityResource.java.e.vm
 */
package com.mycompany.myapp.rest;

import static org.springframework.http.MediaType.APPLICATION_JSON_VALUE;
import static org.springframework.web.bind.annotation.RequestMethod.DELETE;
import static org.springframework.web.bind.annotation.RequestMethod.GET;
import static org.springframework.web.bind.annotation.RequestMethod.POST;
import static org.springframework.web.bind.annotation.RequestMethod.PUT;

import java.net.URI;
import java.net.URISyntaxException;
import java.util.List;
import java.util.Optional;

import javax.inject.Inject;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.bind.annotation.RequestBody;

import com.mycompany.myapp.domain.SupTable;
import com.mycompany.myapp.dto.SupTableDTO;
import com.mycompany.myapp.dto.SupTableDTOService;
import com.mycompany.myapp.dto.support.PageRequestByExample;
import com.mycompany.myapp.dto.support.PageResponse;
import com.mycompany.myapp.repository.SupTableRepository;
import com.mycompany.myapp.rest.support.AutoCompleteQuery;

@RestController
@RequestMapping("/api/supTables")
public class SupTableResource {

    private final Logger log = LoggerFactory.getLogger(SupTableResource.class);

    @Inject
    private SupTableRepository supTableRepository;
    @Inject
    private SupTableDTOService supTableDTOService;

    /**
     * Create a new SupTable.
     */
    @RequestMapping(value = "/", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<SupTableDTO> create(@RequestBody SupTableDTO supTableDTO) throws URISyntaxException {

        log.debug("Create SupTableDTO : {}", supTableDTO);

        if (supTableDTO.isIdSet()) {
            return ResponseEntity.badRequest().header("Failure", "Cannot create SupTable with existing ID").body(null);
        }

        SupTableDTO result = supTableDTOService.save(supTableDTO);

        return ResponseEntity.created(new URI("/api/supTables/" + result.id)).body(result);
    }

    /**
    * Find by id SupTable.
    */
    @RequestMapping(value = "/{id}", method = GET, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<SupTableDTO> findById(@PathVariable Integer id) throws URISyntaxException {

        log.debug("Find by id SupTable : {}", id);

        return Optional.ofNullable(supTableDTOService.findOne(id)).map(supTableDTO -> new ResponseEntity<>(supTableDTO, HttpStatus.OK))
                .orElse(new ResponseEntity<>(HttpStatus.NOT_FOUND));
    }

    /**
     * Update SupTable.
     */
    @RequestMapping(value = "/", method = PUT, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<SupTableDTO> update(@RequestBody SupTableDTO supTableDTO) throws URISyntaxException {

        log.debug("Update SupTableDTO : {}", supTableDTO);

        if (!supTableDTO.isIdSet()) {
            return create(supTableDTO);
        }

        SupTableDTO result = supTableDTOService.save(supTableDTO);

        return ResponseEntity.ok().body(result);
    }

    /**
     * Find a Page of SupTable using query by example.
     */
    @RequestMapping(value = "/page", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<PageResponse<SupTableDTO>> findAll(@RequestBody PageRequestByExample<SupTableDTO> prbe) throws URISyntaxException {
        PageResponse<SupTableDTO> pageResponse = supTableDTOService.findAll(prbe);
        return new ResponseEntity<>(pageResponse, new HttpHeaders(), HttpStatus.OK);
    }

    /**
    * Auto complete support.
    */
    @RequestMapping(value = "/complete", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<List<SupTableDTO>> complete(@RequestBody AutoCompleteQuery acq) throws URISyntaxException {

        List<SupTableDTO> results = supTableDTOService.complete(acq.query, acq.maxResults);

        return new ResponseEntity<>(results, new HttpHeaders(), HttpStatus.OK);
    }

    /**
     * Delete by id SupTable.
     */
    @RequestMapping(value = "/{id}", method = DELETE, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<Void> delete(@PathVariable Integer id) throws URISyntaxException {

        log.debug("Delete by id SupTable : {}", id);

        try {
            supTableRepository.delete(id);
            return ResponseEntity.ok().build();
        } catch (Exception x) {
            // todo: dig exception, most likely org.hibernate.exception.ConstraintViolationException
            return ResponseEntity.status(HttpStatus.CONFLICT).build();
        }
    }
}