//
// Project home: https://github.com/jaxio/celerio-angular-quickstart
// 
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Source code: https://github.com/jaxio/celerio/
// Follow us on twitter: @jaxiosoft
// This header can be customized in Celerio conf...
// Template pack-angular:web/src/app/entities/compositepk.ts.cpk.vm
//

export class UserDetailsPk {
    id : number;
    username : string;

    constructor(json? : any) {
        if (json != null) {
            this.id = json.id;
            this.username = json.username;
        }
    }
}