//
// Project home: https://github.com/jaxio/celerio-angular-quickstart
// 
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Source code: https://github.com/jaxio/celerio/
// Follow us on twitter: @jaxiosoft
// This header can be customized in Celerio conf...
// Template pack-angular:web/src/app/entities/entity.ts.e.vm
//
import {UserDetailsPk} from "./userDetailsPk";

export class UserDetails {
    id : UserDetailsPk = new UserDetailsPk();
    // Raw attributes
    name : string;
    phNumber : number;
    emailId : string;
    parent : string;


    constructor(json? : any) {
        if (json != null) {
            this.id = new UserDetailsPk(json.id);
            this.name = json.name;
            this.phNumber = json.phNumber;
            this.emailId = json.emailId;
            this.parent = json.parent;
        }
    }

    // Utils

    static toArray(jsons : any[]) : UserDetails[] {
        let userDetailss : UserDetails[] = [];
        if (jsons != null) {
            for (let json of jsons) {
                userDetailss.push(new UserDetails(json));
            }
        }
        return userDetailss;
    }
}
