//
// Project home: https://github.com/jaxio/celerio-angular-quickstart
// 
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Source code: https://github.com/jaxio/celerio/
// Follow us on twitter: @jaxiosoft
// This header can be customized in Celerio conf...
// Template pack-angular:web/src/app/entities/entity-list.component.ts.e.vm
//
import { Component, Input, Output, OnChanges, EventEmitter, SimpleChanges } from '@angular/core';
import { Router } from '@angular/router';
import { DataTable, LazyLoadEvent } from 'primeng/primeng';
import { PageResponse } from "../../support/paging";
import { MessageService } from '../../service/message.service';
import { MdDialog } from '@angular/material';
import { ConfirmDeleteDialogComponent } from "../../support/confirm-delete-dialog.component";
import { DisTable } from './disTable';
import { DisTableDetailComponent } from './disTable-detail.component';
import { DisTableService } from './disTable.service';
import { User } from '../user/user';
import { UserLineComponent } from '../user/user-line.component';

@Component({
    moduleId: module.id,
	templateUrl: 'disTable-list.component.html',
	selector: 'disTable-list'
})
export class DisTableListComponent {

    @Input() header = "DisTables...";

    // When 'sub' is true, it means this list is used as a one-to-many list.
    // It belongs to a parent entity, as a result the addNew operation
    // must prefill the parent entity. The prefill is not done here, instead we
    // emit an event.
    // When 'sub' is false, we display basic search criterias
    @Input() sub : boolean;
    @Output() onAddNewClicked = new EventEmitter();

    disTableToDelete : DisTable;

    // basic search criterias (visible if not in 'sub' mode)
    example : DisTable = new DisTable();

    // list is paginated
    currentPage : PageResponse<DisTable> = new PageResponse<DisTable>(0,0,[]);

    // X to one: input param is used to filter the list when displayed
    // as a one-to-many list by the other side.
    private _username : User;

    constructor(private router : Router,
        private disTableService : DisTableService,
        private messageService : MessageService,
        private confirmDeleteDialog: MdDialog) {
    }

    /**
     * When used as a 'sub' component (to display one-to-many list), refreshes the table
     * content when the input changes.
     */
    ngOnChanges(changes: SimpleChanges) {
        this.loadPage({ first: 0, rows: 10, sortField: null, sortOrder: null, filters: null, multiSortMeta: null });
    }

    /**
     * Invoked when user presses the search button.
     */
    search(dt : DataTable) {
        if (!this.sub) {
            dt.reset();
            this.loadPage({ first: 0, rows: dt.rows, sortField: dt.sortField, sortOrder: dt.sortOrder, filters: null, multiSortMeta: dt.multiSortMeta });
        }
    }

    /**
     * Invoked automatically by primeng datatable.
     */
    loadPage(event : LazyLoadEvent) {
        this.disTableService.getPage(this.example, event).
            subscribe(
                pageResponse => this.currentPage = pageResponse,
                error => this.messageService.error('Could not get the results', error)
            );
    }

    // X to one: input param is used to filter the list when displayed
    // as a one-to-many list by the other side.
    @Input()
    set username(username : User) {
        if (username == null) {
            return;
        }
        this._username = username;

        this.example = new DisTable();
        this.example.username = new User();
        this.example.username.id = this._username.id;
    }


    onRowSelect(event : any) {
        let id =  event.data.id;
        this.router.navigate(['/disTable', id]);
    }

    addNew() {
        if (this.sub) {
            this.onAddNewClicked.emit("addNew");
        } else {
            this.router.navigate(['/disTable', 'new']);
        }
    }

    showDeleteDialog(rowData : any) {
        let disTableToDelete : DisTable = <DisTable> rowData;

        let dialogRef = this.confirmDeleteDialog.open(ConfirmDeleteDialogComponent);
        dialogRef.afterClosed().subscribe(result => {
            if (result === 'delete') {
                this.delete(disTableToDelete);
            }
        });
    }

    private delete(disTableToDelete : DisTable) {
        let id =  disTableToDelete.id;

        this.disTableService.delete(id).
            subscribe(
                response => {
                    this.currentPage.remove(disTableToDelete);
                    this.messageService.info('Deleted OK', 'Angular Rocks!');
                },
                error => this.messageService.error('Could not delete!', error)
            );
    }
}