//
// Project home: https://github.com/jaxio/celerio-angular-quickstart
// 
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Source code: https://github.com/jaxio/celerio/
// Follow us on twitter: @jaxiosoft
// This header can be customized in Celerio conf...
// Template pack-angular:web/src/app/entities/entity-detail.component.ts.e.vm
//
import {Component, OnInit, OnDestroy, Input, Output, EventEmitter} from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { SelectItem } from 'primeng/primeng';
import { MessageService} from '../../service/message.service';
import {DisTable} from './disTable';
import {DisTableService} from './disTable.service';
import {User} from '../user/user';

@Component({
    moduleId: module.id,
	templateUrl: 'disTable-detail.component.html',
	selector: 'disTable-detail',
})
export class DisTableDetailComponent implements OnInit, OnDestroy {
    disTable : DisTable;

    private params_subscription: any;


    @Input() sub : boolean = false;
    @Input() // used to pass the parent when creating a new DisTable
    set username(username : User) {
        this.disTable = new DisTable();
        this.disTable.username = username;
    }

    @Output() onSaveClicked = new EventEmitter<DisTable>();
    @Output() onCancelClicked = new EventEmitter();

    constructor(private route: ActivatedRoute, private router: Router, private messageService: MessageService, private disTableService: DisTableService) {
    }

    ngOnInit() {
        if (this.sub) {
            return;
        }

        this.params_subscription = this.route.params.subscribe(params => {
            let id = params['id'];
            console.log('ngOnInit for disTable-detail ' + id);

            if (id === 'new') {
                this.disTable = new DisTable();
            } else {
                this.disTableService.getDisTable(id)
                    .subscribe(disTable => {
                            this.disTable = disTable;
                        },
                        error =>  this.messageService.error('ngOnInit error', error)
                    );
            }
        });
    }

    ngOnDestroy() {
        if (!this.sub) {
            this.params_subscription.unsubscribe();
        }
    }

    gotoUsername() {
        this.router.navigate(['/user', this.disTable.username.id]);
    }

    clearUsername() {
        this.disTable.username = null;
    }

    onSave() {
        this.disTableService.update(this.disTable).
            subscribe(
                disTable => {
                    this.disTable = disTable;
                    if (this.sub) {
                        this.onSaveClicked.emit(this.disTable);
                        this.messageService.info('Saved OK and msg emitted', 'Angular Rocks!')
                    } else {
                        this.messageService.info('Saved OK', 'Angular Rocks!')
                    }
                },
                error =>  this.messageService.error('Could not save', error)
            );
    }

    onCancel() {
        if (this.sub) {
            this.onCancelClicked.emit("cancel");
            this.messageService.info('Cancel clicked and msg emitted', 'Angular Rocks!')
        }
    }

}
