//
// Project home: https://github.com/jaxio/celerio-angular-quickstart
// 
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Source code: https://github.com/jaxio/celerio/
// Follow us on twitter: @jaxiosoft
// This header can be customized in Celerio conf...
// Template pack-angular:web/src/app/entities/entity.service.ts.e.vm
//
import { Injectable } from '@angular/core';
import { HttpModule, Http, Response, Headers, RequestOptions } from '@angular/http';
import { LazyLoadEvent } from 'primeng/primeng';
import { Observable } from 'rxjs/Observable';
import { MessageService } from '../../service/message.service';
import { PageResponse, PageRequestByExample } from '../../support/paging';
import { DisTable } from './disTable';

@Injectable()
export class DisTableService {

    private options = new RequestOptions({ headers: new Headers({ 'Content-Type': 'application/json' }) });

    constructor(private http: Http, private messageService : MessageService) {}

    /**
     * Get a DisTable by id.
     */
    getDisTable(id : any) : Observable<DisTable> {
        return this.http.get('/api/disTables/' + id)
            .map(response => new DisTable(response.json()))
            .catch(this.handleError);
    }

    /**
     * Update the passed disTable.
     */
    update(disTable : DisTable) : Observable<DisTable> {
        let body = JSON.stringify(disTable);

        return this.http.put('/api/disTables/', body, this.options)
            .map(response => new DisTable(response.json()))
            .catch(this.handleError);
    }

    /**
     * Load a page (for paginated datatable) of DisTable using the passed
     * disTable as an example for the search by example facility.
     */
    getPage(disTable : DisTable, event : LazyLoadEvent) : Observable<PageResponse<DisTable>> {
        let req = new PageRequestByExample(disTable, event);
        let body = JSON.stringify(req);

        return this.http.post('/api/disTables/page', body, this.options)
            .map(response => {
                let pr : any = response.json();
                return new PageResponse<DisTable>(pr.totalPages, pr.totalElements, DisTable.toArray(pr.content));
            })
            .catch(this.handleError);
    }

    /**
     * Performs a search by example on 1 attribute (defined on server side) and returns at most 10 results.
     * Used by DisTableCompleteComponent.
     */
    complete(query : string) : Observable<DisTable[]> {
        let body = JSON.stringify({'query': query, 'maxResults': 10});
        return this.http.post('/api/disTables/complete', body, this.options)
            .map(response => DisTable.toArray(response.json()))
            .catch(this.handleError);
    }

    /**
     * Delete an DisTable by id.
     */
    delete(id : any) {
        return this.http.delete('/api/disTables/' + id).catch(this.handleError);
    }

    // sample method from angular doc
    private handleError (error: any) {
        // TODO: seems we cannot use messageService from here...
        let errMsg = (error.message) ? error.message :
        error.status ? `Status: ${error.status} - Text: ${error.statusText}` : 'Server error';
        console.error(errMsg); // log to console instead
        if (error.status === 401 ) {
            window.location.href = '/';
        }
        return Observable.throw(errMsg);
    }
}
