/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/domain/Entity.java.e.vm
 */
package com.mycompany.myapp.domain;

import java.io.Serializable;
import java.util.logging.Logger;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.Digits;
import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.NotEmpty;

import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;

@Entity
@Table(name = "logindetails")
public class Logindetails implements Identifiable<String>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = Logger.getLogger(Logindetails.class.getName());

    // Raw attributes
    private String id;
    private String password;
    private Integer manu;
    private Integer sup;

    @Override
    public String entityClassName() {
        return Logindetails.class.getSimpleName();
    }

    // -- [id] ------------------------

    @Override
    @NotEmpty
    @Size(max = 45)
    @Column(name = "Username", length = 45)
    @Id
    public String getId() {
        return id;
    }

    @Override
    public void setId(String id) {
        this.id = id;
    }

    public Logindetails id(String id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    public boolean isIdSet() {
        return id != null && !id.isEmpty();
    }
    // -- [password] ------------------------

    @Size(max = 45)
    @Column(name = "\"Password\"", length = 45)
    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Logindetails password(String password) {
        setPassword(password);
        return this;
    }
    // -- [manu] ------------------------

    @Digits(integer = 3, fraction = 0)
    @Column(name = "MANU", precision = 3)
    public Integer getManu() {
        return manu;
    }

    public void setManu(Integer manu) {
        this.manu = manu;
    }

    public Logindetails manu(Integer manu) {
        setManu(manu);
        return this;
    }
    // -- [sup] ------------------------

    @Digits(integer = 3, fraction = 0)
    @Column(name = "SUP", precision = 3)
    public Integer getSup() {
        return sup;
    }

    public void setSup(Integer sup) {
        this.sup = sup;
    }

    public Logindetails sup(Integer sup) {
        setSup(sup);
        return this;
    }

    /**
     * Apply the default values.
     */
    public Logindetails withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof Logindetails && hashCode() == other.hashCode());
    }

    private IdentifiableHashBuilder identifiableHashBuilder = new IdentifiableHashBuilder();

    @Override
    public int hashCode() {
        return identifiableHashBuilder.hash(log, this);
    }

    /**
     * Construct a readable string representation for this Logindetails instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this) //
                .add("id", getId()) //
                .add("password", "XXXX") //
                .add("manu", getManu()) //
                .add("sup", getSup()) //
                .toString();
    }
}