/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/domain/Entity.java.e.vm
 */
package com.mycompany.myapp.domain;

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;
import java.time.Instant;
import java.util.logging.Logger;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.Digits;

import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;

@Entity
@Table(name = "sup_table")
public class SupTable implements Identifiable<Integer>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = Logger.getLogger(SupTable.class.getName());

    // Raw attributes
    private Integer id;
    private Integer iv1;
    private Integer iv2;
    private Integer iv3;
    private Instant timestamp;

    @Override
    public String entityClassName() {
        return SupTable.class.getSimpleName();
    }

    // -- [id] ------------------------

    @Override
    @Column(name = "id", precision = 10)
    @GeneratedValue(strategy = IDENTITY)
    @Id
    public Integer getId() {
        return id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    public SupTable id(Integer id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    public boolean isIdSet() {
        return id != null;
    }
    // -- [iv1] ------------------------

    @Digits(integer = 10, fraction = 0)
    @Column(name = "iv1", precision = 10)
    public Integer getIv1() {
        return iv1;
    }

    public void setIv1(Integer iv1) {
        this.iv1 = iv1;
    }

    public SupTable iv1(Integer iv1) {
        setIv1(iv1);
        return this;
    }
    // -- [iv2] ------------------------

    @Digits(integer = 10, fraction = 0)
    @Column(name = "iv2", precision = 10)
    public Integer getIv2() {
        return iv2;
    }

    public void setIv2(Integer iv2) {
        this.iv2 = iv2;
    }

    public SupTable iv2(Integer iv2) {
        setIv2(iv2);
        return this;
    }
    // -- [iv3] ------------------------

    @Digits(integer = 10, fraction = 0)
    @Column(name = "iv3", precision = 10)
    public Integer getIv3() {
        return iv3;
    }

    public void setIv3(Integer iv3) {
        this.iv3 = iv3;
    }

    public SupTable iv3(Integer iv3) {
        setIv3(iv3);
        return this;
    }
    // -- [timestamp] ------------------------

    @Column(name = "\"timestamp\"", length = 19)
    public Instant getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Instant timestamp) {
        this.timestamp = timestamp;
    }

    public SupTable timestamp(Instant timestamp) {
        setTimestamp(timestamp);
        return this;
    }

    /**
     * Apply the default values.
     */
    public SupTable withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof SupTable && hashCode() == other.hashCode());
    }

    private IdentifiableHashBuilder identifiableHashBuilder = new IdentifiableHashBuilder();

    @Override
    public int hashCode() {
        return identifiableHashBuilder.hash(log, this);
    }

    /**
     * Construct a readable string representation for this SupTable instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this) //
                .add("id", getId()) //
                .add("iv1", getIv1()) //
                .add("iv2", getIv2()) //
                .add("iv3", getIv3()) //
                .add("timestamp", getTimestamp()) //
                .toString();
    }
}