/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/domain/EntityMeta_.java.e.vm
 */
package com.mycompany.myapp.domain;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(UserDetails.class)
public abstract class UserDetails_ {
    // Composite primary key
    public static volatile SingularAttribute<UserDetails, UserDetailsPk> id;

    // Raw attributes
    public static volatile SingularAttribute<UserDetails, String> name;
    public static volatile SingularAttribute<UserDetails, Integer> phNumber;
    public static volatile SingularAttribute<UserDetails, String> emailId;
    public static volatile SingularAttribute<UserDetails, String> parent;
}