/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/dto/EntityDTO.java.e.vm
 */
package com.mycompany.myapp.dto;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.mycompany.myapp.domain.UserDetailsPk;

/**
 * Simple DTO for UserDetails.
 */
public class UserDetailsDTO {
    // Composite primary key
    public UserDetailsPk id;
    public String name;
    public Integer phNumber;
    public String emailId;
    public String parent;

    @JsonIgnore
    public boolean isIdSet() {
        return id != null && id.areFieldsSet();
    }
}