//
// Project home: https://github.com/jaxio/celerio-angular-quickstart
// 
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Source code: https://github.com/jaxio/celerio/
// Follow us on twitter: @jaxiosoft
// This header can be customized in Celerio conf...
// Template pack-angular:web/src/app/entities/entity-list.component.ts.e.vm
//
import { Component, Input, Output, OnChanges, EventEmitter, SimpleChanges,OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { DataTable, LazyLoadEvent } from 'primeng/primeng';
import { PageResponse } from "../../support/paging";
import { MessageService } from '../../service/message.service';
import { MdDialog } from '@angular/material';
import { ConfirmDeleteDialogComponent } from "../../support/confirm-delete-dialog.component";
import { ReqTable } from './reqTable';
import { ReqTableDetailComponent } from './reqTable-detail.component';
import { ReqTableService } from './reqTable.service';
import { User } from '../user/user';
import { UserLineComponent } from '../user/user-line.component';

@Component({
    moduleId: module.id,
	templateUrl: 'reqTable-list.component.html',
	selector: 'reqTable-list'
})
export class ReqTableListComponent implements OnInit {

    @Input() header = "ReqTables...";

    // When 'sub' is true, it means this list is used as a one-to-many list.
    // It belongs to a parent entity, as a result the addNew operation
    // must prefill the parent entity. The prefill is not done here, instead we
    // emit an event.
    // When 'sub' is false, we display basic search criterias
    @Input() sub : boolean;
    @Output() onAddNewClicked = new EventEmitter();

    reqTableToDelete : ReqTable;

    // basic search criterias (visible if not in 'sub' mode)
    example : ReqTable = new ReqTable();
    selectedEntities: any[];

    // list is paginated
    currentPage : PageResponse<ReqTable> = new PageResponse<ReqTable>(0,0,[]);

    // X to one: input param is used to filter the list when displayed
    // as a one-to-many list by the other side.
    private _parentName : User;

    constructor(private router : Router,
        private reqTableService : ReqTableService,
        private messageService : MessageService,
        private confirmDeleteDialog: MdDialog) {
    }
    ngOnInit(){
        this.loadPage({ first: 0, rows: 10, sortField: null, sortOrder: null, filters: null, multiSortMeta: null });
    }

    /**
     * When used as a 'sub' component (to display one-to-many list), refreshes the table
     * content when the input changes.
     */
    ngOnChanges(changes: SimpleChanges) {
        this.loadPage({ first: 0, rows: 10, sortField: null, sortOrder: null, filters: null, multiSortMeta: null });
    }

    /**
     * Invoked when user presses the search button.
     */
    search(dt : DataTable) {
        if (!this.sub) {
            dt.reset();
            this.loadPage({ first: 0, rows: dt.rows, sortField: dt.sortField, sortOrder: dt.sortOrder, filters: null, multiSortMeta: dt.multiSortMeta });
        }
    }

    /**
     * Invoked automatically by primeng datatable.
     */
    loadPage(event : LazyLoadEvent) {
        this.reqTableService.getPage(this.example, event).
            subscribe(
                pageResponse => {console.log(pageResponse),this.currentPage = pageResponse},
                error => this.messageService.error('Could not get the results', error)
            );
    }
    public setSelectedEntities($event: any) {
        this.selectedEntities = $event;
    }

    // X to one: input param is used to filter the list when displayed
    // as a one-to-many list by the other side.
    @Input()
    set parentName(parentName : User) {
        if (parentName == null) {
            return;
        }
        this._parentName = parentName;

        this.example = new ReqTable();
        this.example.parentName = new User();
        this.example.parentName.id = this._parentName.id;
    }


    onRowSelect(event : any) {
        let id =  event.data.id;
        this.router.navigate(['/reqTable', id]);
    }

    addNew() {
        if (this.sub) {
            this.onAddNewClicked.emit("addNew");
        } else {
            this.router.navigate(['/reqTable', 'new']);
        }
    }

    showDeleteDialog(rowData : any) {
        let reqTableToDelete : ReqTable = <ReqTable> rowData;

        let dialogRef = this.confirmDeleteDialog.open(ConfirmDeleteDialogComponent);
        dialogRef.afterClosed().subscribe(result => {
            if (result === 'delete') {
                this.delete(reqTableToDelete);
            }
        });
    }

    private delete(reqTableToDelete : ReqTable) {
        let id =  reqTableToDelete.id;

        this.reqTableService.delete(id).
            subscribe(
                response => {
                    this.currentPage.remove(reqTableToDelete);
                    this.messageService.info('Deleted OK', 'Angular Rocks!');
                },
                error => this.messageService.error('Could not delete!', error)
            );
    }
}