//
// Project home: https://github.com/jaxio/celerio-angular-quickstart
// 
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Source code: https://github.com/jaxio/celerio/
// Follow us on twitter: @jaxiosoft
// This header can be customized in Celerio conf...
// Template pack-angular:web/src/app/entities/entity.ts.e.vm
//
import {User} from '../user/user';

export class ReqTable {
    // Raw attributes
    id : number;
    reqBy : string;
    iv1 : number;
    iv2 : number;
    iv3 : number;
    status : boolean;
    // x-to-one
    parentName : User;


    constructor(json? : any) {
        if (json != null) {
            this.id = json.id;
            this.reqBy = json.reqBy;
            this.iv1 = json.iv1;
            this.iv2 = json.iv2;
            this.iv3 = json.iv3;
            this.status = json.status;

            if (json.parentName != null) {
                this.parentName = new User(json.parentName);
            }
        }
    }

    // Utils

    static toArray(jsons : any[]) : ReqTable[] {
        let reqTables : ReqTable[] = [];
        if (jsons != null) {
            for (let json of jsons) {
                reqTables.push(new ReqTable(json));
            }
        }
        return reqTables;
    }
}
