//
// Project home: https://github.com/jaxio/celerio-angular-quickstart
// 
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Source code: https://github.com/jaxio/celerio/
// Follow us on twitter: @jaxiosoft
// This header can be customized in Celerio conf...
// Template pack-angular:web/src/app/entities/entity-detail.component.ts.e.vm
//
import {Component, OnInit, OnDestroy, Input, Output, EventEmitter} from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { SelectItem } from 'primeng/primeng';
import { MessageService} from '../../service/message.service';
import {ReqTable} from './reqTable';
import {ReqTableService} from './reqTable.service';
import {User} from '../user/user';

@Component({
    moduleId: module.id,
	templateUrl: 'reqTable-detail.component.html',
	selector: 'reqTable-detail',
})
export class ReqTableDetailComponent implements OnInit, OnDestroy {
    reqTable : ReqTable;

    private params_subscription: any;


    @Input() sub : boolean = false;
    @Input() // used to pass the parent when creating a new ReqTable
    set parentName(parentName : User) {
        this.reqTable = new ReqTable();
        this.reqTable.parentName = parentName;
    }

    @Output() onSaveClicked = new EventEmitter<ReqTable>();
    @Output() onCancelClicked = new EventEmitter();

    constructor(private route: ActivatedRoute, private router: Router, private messageService: MessageService, private reqTableService: ReqTableService) {
    }

    ngOnInit() {
        if (this.sub) {
            return;
        }

        this.params_subscription = this.route.params.subscribe(params => {
            let id = params['id'];
            console.log('ngOnInit for reqTable-detail ' + id);

            if (id === 'new') {
                this.reqTable = new ReqTable();
            } else {
                this.reqTableService.getReqTable(id)
                    .subscribe(reqTable => {
                            this.reqTable = reqTable;
                        },
                        error =>  this.messageService.error('ngOnInit error', error)
                    );
            }
        });
    }

    ngOnDestroy() {
        if (!this.sub) {
            this.params_subscription.unsubscribe();
        }
    }

    gotoParentName() {
        this.router.navigate(['/user', this.reqTable.parentName.id]);
    }

    clearParentName() {
        this.reqTable.parentName = null;
    }

    onSave() {
        this.reqTableService.update(this.reqTable).
            subscribe(
                reqTable => {
                    this.reqTable = reqTable;
                    if (this.sub) {
                        this.onSaveClicked.emit(this.reqTable);
                        this.messageService.info('Saved OK and msg emitted', 'Angular Rocks!')
                    } else {
                        this.messageService.info('Saved OK', 'Angular Rocks!')
                    }
                },
                error =>  this.messageService.error('Could not save', error)
            );
    }

    onCancel() {
        if (this.sub) {
            this.onCancelClicked.emit("cancel");
            this.messageService.info('Cancel clicked and msg emitted', 'Angular Rocks!')
        }
    }

}
