//
// Project home: https://github.com/jaxio/celerio-angular-quickstart
// 
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Source code: https://github.com/jaxio/celerio/
// Follow us on twitter: @jaxiosoft
// This header can be customized in Celerio conf...
// Template pack-angular:web/src/app/app.routes.ts.p.vm
//
import { ModuleWithProviders }  from '@angular/core';
import { Routes, RouterModule } from '@angular/router';

import { HomeComponent } from './home.component';

import { AuthorListComponent } from './entities/author/author-list.component';
import { AuthorDetailComponent } from './entities/author/author-detail.component';

import { BookListComponent } from './entities/book/book-list.component';
import { BookDetailComponent } from './entities/book/book-detail.component';

import { DisTableListComponent } from './entities/disTable/disTable-list.component';
import { DisTableDetailComponent } from './entities/disTable/disTable-detail.component';

import { ManuTableListComponent } from './entities/manuTable/manuTable-list.component';
import { ManuTableDetailComponent } from './entities/manuTable/manuTable-detail.component';

import { PassportListComponent } from './entities/passport/passport-list.component';
import { PassportDetailComponent } from './entities/passport/passport-detail.component';

import { ProjectListComponent } from './entities/project/project-list.component';
import { ProjectDetailComponent } from './entities/project/project-detail.component';

import { ReqTableListComponent } from './entities/reqTable/reqTable-list.component';
import { ReqTableDetailComponent } from './entities/reqTable/reqTable-detail.component';

import { RoleListComponent } from './entities/role/role-list.component';
import { RoleDetailComponent } from './entities/role/role-detail.component';

import { SupTableListComponent } from './entities/supTable/supTable-list.component';
import { SupTableDetailComponent } from './entities/supTable/supTable-detail.component';

import { UseCase1ListComponent } from './entities/useCase1/useCase1-list.component';
import { UseCase1DetailComponent } from './entities/useCase1/useCase1-detail.component';

import { UseCase2ListComponent } from './entities/useCase2/useCase2-list.component';
import { UseCase2DetailComponent } from './entities/useCase2/useCase2-detail.component';

import { UseCase3ListComponent } from './entities/useCase3/useCase3-list.component';
import { UseCase3DetailComponent } from './entities/useCase3/useCase3-detail.component';

import { UserListComponent } from './entities/user/user-list.component';
import { UserDetailComponent } from './entities/user/user-detail.component';

import { UserDetailsListComponent } from './entities/userDetails/userDetails-list.component';
import { UserDetailsDetailComponent } from './entities/userDetails/userDetails-detail.component';

export const routes: Routes = [
    { path : '',  component: HomeComponent }
    ,
    {path: 'author-list', component: AuthorListComponent },
    {path: 'author/:id', component: AuthorDetailComponent }
    ,
    {path: 'book-list', component: BookListComponent },
    {path: 'book/:id', component: BookDetailComponent }
    ,
    {path: 'disTable-list', component: DisTableListComponent },
    {path: 'disTable/:id', component: DisTableDetailComponent }
    ,
    {path: 'manuTable-list', component: ManuTableListComponent },
    {path: 'manuTable/:id', component: ManuTableDetailComponent }
    ,
    {path: 'passport-list', component: PassportListComponent },
    {path: 'passport/:id', component: PassportDetailComponent }
    ,
    {path: 'project-list', component: ProjectListComponent },
    {path: 'project/:id', component: ProjectDetailComponent }
    ,
    {path: 'reqTable-list', component: ReqTableListComponent },
    {path: 'reqTable/:id', component: ReqTableDetailComponent }
    ,
    {path: 'role-list', component: RoleListComponent },
    {path: 'role/:id', component: RoleDetailComponent }
    ,
    {path: 'supTable-list', component: SupTableListComponent },
    {path: 'supTable/:id', component: SupTableDetailComponent }
    ,
    {path: 'useCase1-list', component: UseCase1ListComponent },
    {path: 'useCase1/:id', component: UseCase1DetailComponent }
    ,
    {path: 'useCase2-list', component: UseCase2ListComponent },
    {path: 'useCase2/:id', component: UseCase2DetailComponent }
    ,
    {path: 'useCase3-list', component: UseCase3ListComponent },
    {path: 'useCase3/:id', component: UseCase3DetailComponent }
    ,
    {path: 'user-list', component: UserListComponent },
    {path: 'user/:id', component: UserDetailComponent }
    ,
    {path: 'userDetails-list', component: UserDetailsListComponent },
    {path: 'userDetails/:id', component: UserDetailsDetailComponent }
];

export const routing: ModuleWithProviders = RouterModule.forRoot(routes);
