//
// Project home: https://github.com/jaxio/celerio-angular-quickstart
// 
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Source code: https://github.com/jaxio/celerio/
// Follow us on twitter: @jaxiosoft
// This header can be customized in Celerio conf...
// Template pack-angular:web/src/app/entities/entity.ts.e.vm
//

export class Logindetails {
    // Raw attributes
    id : string;
    password : string;
    manu : number;
    sup : number;


    constructor(json? : any) {
        if (json != null) {
            this.id = json.id;
            this.password = json.password;
            this.manu = json.manu;
            this.sup = json.sup;
        }
    }

    // Utils

    static toArray(jsons : any[]) : Logindetails[] {
        let logindetailss : Logindetails[] = [];
        if (jsons != null) {
            for (let json of jsons) {
                logindetailss.push(new Logindetails(json));
            }
        }
        return logindetailss;
    }
}
